version: '2'

services:
    drupal-server:
        image: drupal:8.8.2
        ports:
            - 8080:80
        volumes:
            # See docker-compose docs for long syntax
            - drupal_modules:/var/www/html/modules
            - drupal_profiles:/var/www/html/profiles
            - drupal_themes:/var/www/html/themes
            - drupal_sites:/var/www/html/sites

    drupal-postgres-db:
        image: postgres:12.1
        environment:
            POSTGRES_DB: drupal
            POSTGRES_USER: root
            POSTGRES_PASSWORD: Password#1
        volumes:
            - drupal_postgred_db:/var/lib/postgresql/data

# Named volumes
volumes:
    drupal_modules:
    drupal_profiles:
    drupal_themes:
    drupal_sites:
    drupal_postgred_db: