# create your drupal and postgres config here, based off the last assignment
# implementing docker stack with secrets

version: '3.1'

services:
    drupal-server:
        image: drupal:8.2
        ports:
            - 8080:80
        volumes:
            - drupal_modules:/var/www/html/modules
            - drupal_profiles:/var/www/html/profiles
            - drupal_themes:/var/www/html/themes
            - drupal_sites:/var/www/html/sites

    drupal-postgres-db:
        image: postgres:12.1
        environment:
            POSTGRES_DB: drupal
            POSTGRES_USER: root
            POSTGRES_PASSWORD_FILE: /run/secrets/psql_password
        secrets:
            - psql_password
        volumes:
            - drupal_postgres_db:/var/lib/postgresql/data

volumes:
    drupal_modules:
    drupal_profiles:
    drupal_themes:
    drupal_sites:
    drupal_postgres_db:

secrets:
    psql_password:
        external: true
